### ISSUE TITLE
make search bar persistent 

### ISSUE THREAD

**Issue by TristinRohr** [TristinRohr/NexusInsight#38]
Make the search bar available on all pages no matter what

**Comment by sfonua10** [comment]
### User Story:
As a user, I want the search bar to be available on all pages within the League of Legends Tracker app so that I can easily search for summoner stats without having to navigate to the search page.

### Acceptance Criteria:
**Search Bar Availability:**

The search bar (from Search.jsx) should be visible and functional on every page (e.g., Profile, MatchHistory, FavoriteFeed).
The search bar should retain its input values (summonerName and tagLine) across all navigations unless manually changed.

**Functional Behavior:**

When submitting a search, the app should navigate to /match-history and display stats using the provided summonerName and tagLine (displayed via UserStats, MatchHistory, and LiveMatch components).
The onSearch function should update the global state for summonerName and tagLine, ensuring the search is consistent across pages.

**Persistence:**

When navigating between pages (e.g., from Profile to MatchHistory), the search bar should maintain the previous search inputs unless a new search is performed.
The application should ensure that when revisiting pages after searching, the summoner's information remains correctly populated.

**Global State Management:**

The state (summonerName and tagLine) should be maintained at the App.jsx level to ensure search results are accessible across different components (like MatchHistory and Profile).

**UI/UX Consistency:**

The search bar should be consistently placed, such as in a fixed header or navigation bar.
It should be easily accessible on all screen sizes, including mobile.

**Routing:**

The user should be redirected to /match-history after submitting the search on any page.
If a user manually navigates to /match-history without performing a search, they should be redirected to /search.

**Testing:**

Ensure the search functionality works correctly on all routes (/profile, /match-history, /favorite-feed).
Test to ensure the search bar inputs persist and that navigating between pages doesn’t clear the state unexpectedly.

**Comment by sfonua10** [comment]
https://github.com/TristinRohr/NexusInsight/pull/45
